use crate::instruction::{Instruction, InstructionName, InstructionArg};
use crate::instruction::InstructionName::*;
use crate::instruction::InstructionArg::*;

#[rustfmt_skip]
fn instructions() -> Vec<Instruction> {
    vec![Instruction::new(0x00, Nop, 1, 4, 4),
         Instruction::new(0x01, Ld(Direct16("BC".to_string()), U16), 3, 12, 12),
         Instruction::new(0x02, Ld(Indirect16("BC".to_string()), Direct8("A".to_string())), 1, 8, 8),
         Instruction::new(0x03, Inc(Direct16("BC".to_string())), 1, 8, 8),
         Instruction::new(0x04, Inc(Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x05, Dec(Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x06, Ld(Direct8("B".to_string()), U8), 2, 8, 8),
         Instruction::new(0x07, Rlca, 1, 4, 4),
         Instruction::new(0x08, Ld(IndirectU16, Direct16("SP".to_string())), 3, 20, 20),
         Instruction::new(0x09, Add(Direct16("HL".to_string()), Direct16("BC".to_string())), 1, 8, 8),
         Instruction::new(0x0A, Ld(Direct8("A".to_string()), Indirect16("BC".to_string())), 1, 8, 8),
         Instruction::new(0x0B, Dec(Direct16("BC".to_string())), 1, 8, 8),
         Instruction::new(0x0C, Inc(Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x0D, Dec(Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x0E, Ld(Direct8("C".to_string()), U8), 2, 8, 8),
         Instruction::new(0x0F, Rrca, 1, 4, 4),
         Instruction::new(0x10, Stop, 1, 4, 4),
         Instruction::new(0x11, Ld(Direct16("DE".to_string()), U16), 3, 12, 12),
         Instruction::new(0x12, Ld(Indirect16("DE".to_string()), Direct8("A".to_string())), 1, 8, 8),
         Instruction::new(0x13, Inc(Direct16("DE".to_string())), 1, 8, 8),
         Instruction::new(0x14, Inc(Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x15, Dec(Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x16, Ld(Direct8("D".to_string()), U8), 2, 8, 8),
         Instruction::new(0x17, Rla, 1, 4, 4),
         Instruction::new(0x18, Jr(I8), 2, 12, 12),
         Instruction::new(0x19, Add(Direct16("HL".to_string()), Direct16("DE".to_string())), 1, 8, 8),
         Instruction::new(0x1A, Ld(Direct8("A".to_string()), Indirect16("DE".to_string())), 1, 8, 8),
         Instruction::new(0x1B, Dec(Direct16("DE".to_string())), 1, 8, 8),
         Instruction::new(0x1C, Inc(Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x1D, Dec(Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x1E, Ld(Direct8("E".to_string()), U8), 2, 8, 8),
         Instruction::new(0x1F, Rra, 1, 4, 4),
         Instruction::new(0x20, Jr(Condition("NZ".to_string())), 2, 12, 8),
         Instruction::new(0x21, Ld(Direct16("HL".to_string()), U16), 3, 12, 12),
         Instruction::new(0x22, Ld(Hli, Direct8("A".to_string())), 1, 8, 8),
         Instruction::new(0x23, Inc(Direct16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x24, Inc(Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x25, Dec(Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x26, Ld(Direct8("H".to_string()), U8), 2, 8, 8),
         Instruction::new(0x27, Daa, 1, 4, 4),
         Instruction::new(0x28, Jr(Condition("Z".to_string())), 2, 12, 8),
         Instruction::new(0x29, Add(Direct16("HL".to_string()), Direct16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x2A, Ld(Direct8("A".to_string()), Hli), 1, 8, 8),
         Instruction::new(0x2B, Dec(Direct16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x2C, Inc(Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x2D, Dec(Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x2E, Ld(Direct8("L".to_string()), U8), 2, 8, 8),
         Instruction::new(0x2F, Cpl, 1, 4, 4),
         Instruction::new(0x30, Jr(Condition("NC".to_string())), 2, 12, 8),
         Instruction::new(0x31, Ld(Direct16("SP".to_string()), U16), 3, 12, 12),
         Instruction::new(0x32, Ld(Hld, Direct8("A".to_string())), 1, 8, 8),
         Instruction::new(0x33, Inc(Direct16("SP".to_string())), 1, 8, 8),
         Instruction::new(0x34, Inc(Indirect16("HL".to_string())), 1, 12, 12),
         Instruction::new(0x35, Dec(Indirect16("HL".to_string())), 1, 12, 12),
         Instruction::new(0x36, Ld(Indirect16("HL".to_string()), U8), 2, 12, 12),
         Instruction::new(0x37, Scf, 1, 4, 4),
         Instruction::new(0x38, Jr(Condition("C".to_string())), 2, 12, 8),
         Instruction::new(0x39, Add(Direct16("HL".to_string()), Direct16("SP".to_string())), 1, 8, 8),
         Instruction::new(0x3A, Ld(Direct8("A".to_string()), Hld), 1, 8, 8),
         Instruction::new(0x3B, Dec(Direct16("SP".to_string())), 1, 8, 8),
         Instruction::new(0x3C, Inc(Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x3D, Dec(Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x3E, Ld(Direct8("A".to_string()), U8), 2, 8, 8),
         Instruction::new(0x3F, Ccf, 1, 4, 4),
         Instruction::new(0x40, Ld(Direct8("B".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x41, Ld(Direct8("B".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x42, Ld(Direct8("B".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x43, Ld(Direct8("B".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x44, Ld(Direct8("B".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x45, Ld(Direct8("B".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x46, Ld(Direct8("B".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x47, Ld(Direct8("B".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x48, Ld(Direct8("C".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x49, Ld(Direct8("C".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x4A, Ld(Direct8("C".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x4B, Ld(Direct8("C".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x4C, Ld(Direct8("C".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x4D, Ld(Direct8("C".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x4E, Ld(Direct8("C".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x4F, Ld(Direct8("C".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x50, Ld(Direct8("D".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x51, Ld(Direct8("D".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x52, Ld(Direct8("D".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x53, Ld(Direct8("D".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x54, Ld(Direct8("D".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x55, Ld(Direct8("D".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x56, Ld(Direct8("D".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x57, Ld(Direct8("D".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x58, Ld(Direct8("E".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x59, Ld(Direct8("E".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x5A, Ld(Direct8("E".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x5B, Ld(Direct8("E".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x5C, Ld(Direct8("E".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x5D, Ld(Direct8("E".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x5E, Ld(Direct8("E".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x5F, Ld(Direct8("E".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x60, Ld(Direct8("H".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x61, Ld(Direct8("H".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x62, Ld(Direct8("H".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x63, Ld(Direct8("H".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x64, Ld(Direct8("H".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x65, Ld(Direct8("H".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x66, Ld(Direct8("H".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x67, Ld(Direct8("H".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x68, Ld(Direct8("L".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x69, Ld(Direct8("L".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x6A, Ld(Direct8("L".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x6B, Ld(Direct8("L".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x6C, Ld(Direct8("L".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x6D, Ld(Direct8("L".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x6E, Ld(Direct8("L".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x6F, Ld(Direct8("L".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x70, Ld(Indirect16("HL".to_string()), Direct8("B".to_string())), 1, 8, 8),
         Instruction::new(0x71, Ld(Indirect16("HL".to_string()), Direct8("C".to_string())), 1, 8, 8),
         Instruction::new(0x72, Ld(Indirect16("HL".to_string()), Direct8("D".to_string())), 1, 8, 8),
         Instruction::new(0x73, Ld(Indirect16("HL".to_string()), Direct8("E".to_string())), 1, 8, 8),
         Instruction::new(0x74, Ld(Indirect16("HL".to_string()), Direct8("H".to_string())), 1, 8, 8),
         Instruction::new(0x75, Ld(Indirect16("HL".to_string()), Direct8("L".to_string())), 1, 8, 8),
         Instruction::new(0x76, Halt, 1, 4, 4),
         Instruction::new(0x77, Ld(Indirect16("HL".to_string()), Direct8("A".to_string())), 1, 8, 8),
         Instruction::new(0x78, Ld(Direct8("A".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x79, Ld(Direct8("A".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x7A, Ld(Direct8("A".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x7B, Ld(Direct8("A".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x7C, Ld(Direct8("A".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x7D, Ld(Direct8("A".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x7E, Ld(Direct8("A".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x7F, Ld(Direct8("A".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x80, Add(Direct8("A".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x81, Add(Direct8("A".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x82, Add(Direct8("A".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x83, Add(Direct8("A".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x84, Add(Direct8("A".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x85, Add(Direct8("A".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x86, Add(Direct8("A".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x87, Add(Direct8("A".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x88, Adc(Direct8("A".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x89, Adc(Direct8("A".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x8A, Adc(Direct8("A".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x8B, Adc(Direct8("A".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x8C, Adc(Direct8("A".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x8D, Adc(Direct8("A".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x8E, Adc(Direct8("A".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x8F, Adc(Direct8("A".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x90, Sub(Direct8("A".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x91, Sub(Direct8("A".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x92, Sub(Direct8("A".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x93, Sub(Direct8("A".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x94, Sub(Direct8("A".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x95, Sub(Direct8("A".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x96, Sub(Direct8("A".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x97, Sub(Direct8("A".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0x98, Sbc(Direct8("A".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0x99, Sbc(Direct8("A".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0x9A, Sbc(Direct8("A".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0x9B, Sbc(Direct8("A".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0x9C, Sbc(Direct8("A".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0x9D, Sbc(Direct8("A".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0x9E, Sbc(Direct8("A".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0x9F, Sbc(Direct8("A".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0xA0, And(Direct8("A".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0xA1, And(Direct8("A".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0xA2, And(Direct8("A".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0xA3, And(Direct8("A".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0xA4, And(Direct8("A".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0xA5, And(Direct8("A".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0xA6, And(Direct8("A".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0xA7, And(Direct8("A".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0xA8, Xor(Direct8("A".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0xA9, Xor(Direct8("A".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0xAA, Xor(Direct8("A".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0xAB, Xor(Direct8("A".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0xAC, Xor(Direct8("A".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0xAD, Xor(Direct8("A".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0xAE, Xor(Direct8("A".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0xAF, Xor(Direct8("A".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0xB0, Or(Direct8("A".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0xB1, Or(Direct8("A".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0xB2, Or(Direct8("A".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0xB3, Or(Direct8("A".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0xB4, Or(Direct8("A".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0xB5, Or(Direct8("A".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0xB6, Or(Direct8("A".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0xB7, Or(Direct8("A".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0xB8, Cp(Direct8("A".to_string()), Direct8("B".to_string())), 1, 4, 4),
         Instruction::new(0xB9, Cp(Direct8("A".to_string()), Direct8("C".to_string())), 1, 4, 4),
         Instruction::new(0xBA, Cp(Direct8("A".to_string()), Direct8("D".to_string())), 1, 4, 4),
         Instruction::new(0xBB, Cp(Direct8("A".to_string()), Direct8("E".to_string())), 1, 4, 4),
         Instruction::new(0xBC, Cp(Direct8("A".to_string()), Direct8("H".to_string())), 1, 4, 4),
         Instruction::new(0xBD, Cp(Direct8("A".to_string()), Direct8("L".to_string())), 1, 4, 4),
         Instruction::new(0xBE, Cp(Direct8("A".to_string()), Indirect16("HL".to_string())), 1, 8, 8),
         Instruction::new(0xBF, Cp(Direct8("A".to_string()), Direct8("A".to_string())), 1, 4, 4),
         Instruction::new(0xC0, Ret, 1, 20, 8),
         Instruction::new(0xC1, Pop(Direct16("BC".to_string())), 1, 12, 12),
         Instruction::new(0xC2, Jp(Condition("NZ".to_string())), 3, 16, 12),
         Instruction::new(0xC3, Jp(U16), 3, 16, 16),
         Instruction::new(0xC4, Call(Condition("NZ".to_string())), 3, 24, 12),
         Instruction::new(0xC5, Push(Direct16("BC".to_string())), 1, 16, 16),
         Instruction::new(0xC6, Add(Direct8("A".to_string()), U8), 2, 8, 8),
         Instruction::new(0xC7, Rst(Vec("00h".to_string())), 1, 16, 16),
         Instruction::new(0xC8, Ret, 1, 20, 8),
         Instruction::new(0xC9, Ret, 1, 16, 16),
         Instruction::new(0xCA, Jp(Condition("Z".to_string())), 3, 16, 12),
         Instruction::new(0xCC, Call(Condition("Z".to_string())), 3, 24, 12),
         Instruction::new(0xCD, Call(U16), 3, 24, 24),
         Instruction::new(0xCE, Adc(Direct8("A".to_string()), U8), 2, 8, 8),
         Instruction::new(0xCF, Rst(Vec("08h".to_string())), 1, 16, 16),
         Instruction::new(0xD0, Ret, 1, 20, 8),
         Instruction::new(0xD1, Pop(Direct16("DE".to_string())), 1, 12, 12),
         Instruction::new(0xD2, Jp(Condition("NC".to_string())), 3, 16, 12),
         Instruction::new(0xD4, Call(Condition("NC".to_string())), 3, 24, 12),
         Instruction::new(0xD5, Push(Direct16("DE".to_string())), 1, 16, 16),
         Instruction::new(0xD6, Sub(Direct8("A".to_string()), U8), 2, 8, 8),
         Instruction::new(0xD7, Rst(Vec("10h".to_string())), 1, 16, 16),
         Instruction::new(0xD8, Ret, 1, 20, 8),
         Instruction::new(0xD9, Reti, 1, 16, 16),
         Instruction::new(0xDA, Jp(Condition("C".to_string())), 3, 16, 12),
         Instruction::new(0xDC, Call(Condition("C".to_string())), 3, 24, 12),
         Instruction::new(0xDE, Sbc(Direct8("A".to_string()), U8), 2, 8, 8),
         Instruction::new(0xDF, Rst(Vec("18h".to_string())), 1, 16, 16),
         Instruction::new(0xE0, Ld(IndirectFF00PlusU8, Direct8("A".to_string())), 2, 12, 12),
         Instruction::new(0xE1, Pop(Direct16("HL".to_string())), 1, 12, 12),
         Instruction::new(0xE2, Ld(IndirectFF00PlusC, Direct8("A".to_string())), 1, 8, 8),
         Instruction::new(0xE5, Push(Direct16("HL".to_string())), 1, 16, 16),
         Instruction::new(0xE6, And(Direct8("A".to_string()), U8), 2, 8, 8),
         Instruction::new(0xE7, Rst(Vec("20h".to_string())), 1, 16, 16),
         Instruction::new(0xE8, Add(Direct16("SP".to_string()), I8), 2, 16, 16),
         Instruction::new(0xE9, Jp(Direct16("HL".to_string())), 1, 4, 4),
         Instruction::new(0xEA, Ld(IndirectU16, Direct8("A".to_string())), 3, 16, 16),
         Instruction::new(0xEE, Xor(Direct8("A".to_string()), U8), 2, 8, 8),
         Instruction::new(0xEF, Rst(Vec("28h".to_string())), 1, 16, 16),
         Instruction::new(0xF0, Ld(Direct8("A".to_string()), IndirectFF00PlusU8), 2, 12, 12),
         Instruction::new(0xF1, Pop(Direct16("AF".to_string())), 1, 12, 12),
         Instruction::new(0xF2, Ld(Direct8("A".to_string()), IndirectFF00PlusC), 1, 8, 8),
         Instruction::new(0xF3, Di, 1, 4, 4),
         Instruction::new(0xF5, Push(Direct16("AF".to_string())), 1, 16, 16),
         Instruction::new(0xF6, Or(Direct8("A".to_string()), U8), 2, 8, 8),
         Instruction::new(0xF7, Rst(Vec("30h".to_string())), 1, 16, 16),
         Instruction::new(0xF8, Ld(Direct16("HL".to_string()), SpPlusI8), 2, 12, 12),
         Instruction::new(0xF9, Ld(Direct16("SP".to_string()), Direct16("HL".to_string())), 1, 8, 8),
         Instruction::new(0xFA, Ld(Direct8("A".to_string()), IndirectU16), 3, 16, 16),
         Instruction::new(0xFB, Ei, 1, 4, 4),
         Instruction::new(0xFE, Cp(Direct8("A".to_string()), U8), 2, 8, 8),
         Instruction::new(0xFF, Rst(Vec("38h".to_string())), 1, 16, 16),
         Instruction::new(0xCB00, Rlc(Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB01, Rlc(Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB02, Rlc(Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB03, Rlc(Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB04, Rlc(Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB05, Rlc(Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB06, Rlc(Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB07, Rlc(Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB08, Rrc(Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB09, Rrc(Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB0A, Rrc(Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB0B, Rrc(Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB0C, Rrc(Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB0D, Rrc(Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB0E, Rrc(Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB0F, Rrc(Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB10, Rl(Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB11, Rl(Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB12, Rl(Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB13, Rl(Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB14, Rl(Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB15, Rl(Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB16, Rl(Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB17, Rl(Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB18, Rr(Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB19, Rr(Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB1A, Rr(Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB1B, Rr(Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB1C, Rr(Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB1D, Rr(Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB1E, Rr(Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB1F, Rr(Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB20, Sla(Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB21, Sla(Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB22, Sla(Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB23, Sla(Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB24, Sla(Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB25, Sla(Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB26, Sla(Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB27, Sla(Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB28, Sra(Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB29, Sra(Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB2A, Sra(Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB2B, Sra(Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB2C, Sra(Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB2D, Sra(Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB2E, Sra(Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB2F, Sra(Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB30, Swap(Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB31, Swap(Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB32, Swap(Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB33, Swap(Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB34, Swap(Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB35, Swap(Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB36, Swap(Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB37, Swap(Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB38, Srl(Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB39, Srl(Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB3A, Srl(Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB3B, Srl(Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB3C, Srl(Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB3D, Srl(Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB3E, Srl(Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB3F, Srl(Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB40, Bit(Literal(0), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB41, Bit(Literal(0), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB42, Bit(Literal(0), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB43, Bit(Literal(0), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB44, Bit(Literal(0), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB45, Bit(Literal(0), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB46, Bit(Literal(0), Indirect16("HL".to_string())), 2, 12, 12),
         Instruction::new(0xCB47, Bit(Literal(0), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB48, Bit(Literal(1), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB49, Bit(Literal(1), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB4A, Bit(Literal(1), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB4B, Bit(Literal(1), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB4C, Bit(Literal(1), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB4D, Bit(Literal(1), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB4E, Bit(Literal(1), Indirect16("HL".to_string())), 2, 12, 12),
         Instruction::new(0xCB4F, Bit(Literal(1), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB50, Bit(Literal(2), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB51, Bit(Literal(2), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB52, Bit(Literal(2), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB53, Bit(Literal(2), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB54, Bit(Literal(2), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB55, Bit(Literal(2), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB56, Bit(Literal(2), Indirect16("HL".to_string())), 2, 12, 12),
         Instruction::new(0xCB57, Bit(Literal(2), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB58, Bit(Literal(3), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB59, Bit(Literal(3), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB5A, Bit(Literal(3), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB5B, Bit(Literal(3), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB5C, Bit(Literal(3), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB5D, Bit(Literal(3), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB5E, Bit(Literal(3), Indirect16("HL".to_string())), 2, 12, 12),
         Instruction::new(0xCB5F, Bit(Literal(3), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB60, Bit(Literal(4), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB61, Bit(Literal(4), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB62, Bit(Literal(4), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB63, Bit(Literal(4), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB64, Bit(Literal(4), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB65, Bit(Literal(4), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB66, Bit(Literal(4), Indirect16("HL".to_string())), 2, 12, 12),
         Instruction::new(0xCB67, Bit(Literal(4), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB68, Bit(Literal(5), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB69, Bit(Literal(5), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB6A, Bit(Literal(5), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB6B, Bit(Literal(5), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB6C, Bit(Literal(5), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB6D, Bit(Literal(5), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB6E, Bit(Literal(5), Indirect16("HL".to_string())), 2, 12, 12),
         Instruction::new(0xCB6F, Bit(Literal(5), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB70, Bit(Literal(6), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB71, Bit(Literal(6), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB72, Bit(Literal(6), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB73, Bit(Literal(6), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB74, Bit(Literal(6), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB75, Bit(Literal(6), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB76, Bit(Literal(6), Indirect16("HL".to_string())), 2, 12, 12),
         Instruction::new(0xCB77, Bit(Literal(6), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB78, Bit(Literal(7), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB79, Bit(Literal(7), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB7A, Bit(Literal(7), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB7B, Bit(Literal(7), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB7C, Bit(Literal(7), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB7D, Bit(Literal(7), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB7E, Bit(Literal(7), Indirect16("HL".to_string())), 2, 12, 12),
         Instruction::new(0xCB7F, Bit(Literal(7), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB80, Res(Literal(0), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB81, Res(Literal(0), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB82, Res(Literal(0), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB83, Res(Literal(0), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB84, Res(Literal(0), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB85, Res(Literal(0), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB86, Res(Literal(0), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB87, Res(Literal(0), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB88, Res(Literal(1), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB89, Res(Literal(1), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB8A, Res(Literal(1), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB8B, Res(Literal(1), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB8C, Res(Literal(1), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB8D, Res(Literal(1), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB8E, Res(Literal(1), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB8F, Res(Literal(1), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB90, Res(Literal(2), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB91, Res(Literal(2), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB92, Res(Literal(2), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB93, Res(Literal(2), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB94, Res(Literal(2), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB95, Res(Literal(2), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB96, Res(Literal(2), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB97, Res(Literal(2), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCB98, Res(Literal(3), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCB99, Res(Literal(3), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCB9A, Res(Literal(3), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCB9B, Res(Literal(3), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCB9C, Res(Literal(3), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCB9D, Res(Literal(3), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCB9E, Res(Literal(3), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCB9F, Res(Literal(3), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBA0, Res(Literal(4), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBA1, Res(Literal(4), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBA2, Res(Literal(4), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBA3, Res(Literal(4), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBA4, Res(Literal(4), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBA5, Res(Literal(4), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBA6, Res(Literal(4), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBA7, Res(Literal(4), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBA8, Res(Literal(5), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBA9, Res(Literal(5), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBAA, Res(Literal(5), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBAB, Res(Literal(5), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBAC, Res(Literal(5), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBAD, Res(Literal(5), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBAE, Res(Literal(5), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBAF, Res(Literal(5), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBB0, Res(Literal(6), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBB1, Res(Literal(6), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBB2, Res(Literal(6), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBB3, Res(Literal(6), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBB4, Res(Literal(6), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBB5, Res(Literal(6), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBB6, Res(Literal(6), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBB7, Res(Literal(6), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBB8, Res(Literal(7), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBB9, Res(Literal(7), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBBA, Res(Literal(7), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBBB, Res(Literal(7), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBBC, Res(Literal(7), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBBD, Res(Literal(7), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBBE, Res(Literal(7), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBBF, Res(Literal(7), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBC0, Set(Literal(0), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBC1, Set(Literal(0), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBC2, Set(Literal(0), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBC3, Set(Literal(0), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBC4, Set(Literal(0), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBC5, Set(Literal(0), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBC6, Set(Literal(0), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBC7, Set(Literal(0), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBC8, Set(Literal(1), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBC9, Set(Literal(1), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBCA, Set(Literal(1), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBCB, Set(Literal(1), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBCC, Set(Literal(1), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBCD, Set(Literal(1), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBCE, Set(Literal(1), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBCF, Set(Literal(1), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBD0, Set(Literal(2), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBD1, Set(Literal(2), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBD2, Set(Literal(2), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBD3, Set(Literal(2), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBD4, Set(Literal(2), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBD5, Set(Literal(2), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBD6, Set(Literal(2), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBD7, Set(Literal(2), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBD8, Set(Literal(3), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBD9, Set(Literal(3), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBDA, Set(Literal(3), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBDB, Set(Literal(3), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBDC, Set(Literal(3), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBDD, Set(Literal(3), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBDE, Set(Literal(3), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBDF, Set(Literal(3), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBE0, Set(Literal(4), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBE1, Set(Literal(4), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBE2, Set(Literal(4), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBE3, Set(Literal(4), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBE4, Set(Literal(4), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBE5, Set(Literal(4), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBE6, Set(Literal(4), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBE7, Set(Literal(4), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBE8, Set(Literal(5), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBE9, Set(Literal(5), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBEA, Set(Literal(5), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBEB, Set(Literal(5), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBEC, Set(Literal(5), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBED, Set(Literal(5), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBEE, Set(Literal(5), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBEF, Set(Literal(5), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBF0, Set(Literal(6), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBF1, Set(Literal(6), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBF2, Set(Literal(6), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBF3, Set(Literal(6), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBF4, Set(Literal(6), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBF5, Set(Literal(6), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBF6, Set(Literal(6), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBF7, Set(Literal(6), Direct8("A".to_string())), 2, 8, 8),
         Instruction::new(0xCBF8, Set(Literal(7), Direct8("B".to_string())), 2, 8, 8),
         Instruction::new(0xCBF9, Set(Literal(7), Direct8("C".to_string())), 2, 8, 8),
         Instruction::new(0xCBFA, Set(Literal(7), Direct8("D".to_string())), 2, 8, 8),
         Instruction::new(0xCBFB, Set(Literal(7), Direct8("E".to_string())), 2, 8, 8),
         Instruction::new(0xCBFC, Set(Literal(7), Direct8("H".to_string())), 2, 8, 8),
         Instruction::new(0xCBFD, Set(Literal(7), Direct8("L".to_string())), 2, 8, 8),
         Instruction::new(0xCBFE, Set(Literal(7), Indirect16("HL".to_string())), 2, 16, 16),
         Instruction::new(0xCBFF, Set(Literal(7), Direct8("A".to_string())), 2, 8, 8), ]
}