use crate::instruction::InstructionArg::*;
use crate::instruction::InstructionName::*;
use crate::instruction::{Instruction, InstructionArg, InstructionName};

pub fn new() -> Vec<Instruction> {
    vec![
        Instruction::new(0x00, Nop, 1, 4, 4),
        Instruction::new(0x01, Ld(DirectRegister16("BC".to_string()), U16), 3, 12, 12),
        Instruction::new(
            0x02,
            Ld(
                IndirectRegister16("BC".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(0x03, Inc(DirectRegister16("BC".to_string())), 1, 8, 8),
        Instruction::new(0x04, Inc(DirectRegister8("B".to_string())), 1, 4, 4),
        Instruction::new(0x05, Dec(DirectRegister8("B".to_string())), 1, 4, 4),
        Instruction::new(0x06, Ld(DirectRegister8("B".to_string()), U8), 2, 8, 8),
        Instruction::new(0x07, Rlca, 1, 4, 4),
        Instruction::new(
            0x08,
            Ld(IndirectU16, DirectRegister16("SP".to_string())),
            3,
            20,
            20,
        ),
        Instruction::new(
            0x09,
            Add(
                DirectRegister16("HL".to_string()),
                DirectRegister16("BC".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x0A,
            Ld(
                DirectRegister8("A".to_string()),
                IndirectRegister16("BC".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(0x0B, Dec(DirectRegister16("BC".to_string())), 1, 8, 8),
        Instruction::new(0x0C, Inc(DirectRegister8("C".to_string())), 1, 4, 4),
        Instruction::new(0x0D, Dec(DirectRegister8("C".to_string())), 1, 4, 4),
        Instruction::new(0x0E, Ld(DirectRegister8("C".to_string()), U8), 2, 8, 8),
        Instruction::new(0x0F, Rrca, 1, 4, 4),
        Instruction::new(0x10, Stop, 1, 4, 4),
        Instruction::new(0x11, Ld(DirectRegister16("DE".to_string()), U16), 3, 12, 12),
        Instruction::new(
            0x12,
            Ld(
                IndirectRegister16("DE".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(0x13, Inc(DirectRegister16("DE".to_string())), 1, 8, 8),
        Instruction::new(0x14, Inc(DirectRegister8("D".to_string())), 1, 4, 4),
        Instruction::new(0x15, Dec(DirectRegister8("D".to_string())), 1, 4, 4),
        Instruction::new(0x16, Ld(DirectRegister8("D".to_string()), U8), 2, 8, 8),
        Instruction::new(0x17, Rla, 1, 4, 4),
        Instruction::new(0x18, Jr(I8), 2, 12, 12),
        Instruction::new(
            0x19,
            Add(
                DirectRegister16("HL".to_string()),
                DirectRegister16("DE".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x1A,
            Ld(
                DirectRegister8("A".to_string()),
                IndirectRegister16("DE".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(0x1B, Dec(DirectRegister16("DE".to_string())), 1, 8, 8),
        Instruction::new(0x1C, Inc(DirectRegister8("E".to_string())), 1, 4, 4),
        Instruction::new(0x1D, Dec(DirectRegister8("E".to_string())), 1, 4, 4),
        Instruction::new(0x1E, Ld(DirectRegister8("E".to_string()), U8), 2, 8, 8),
        Instruction::new(0x1F, Rra, 1, 4, 4),
        Instruction::new(0x20, Jr(Condition("NZ".to_string())), 2, 12, 8),
        Instruction::new(0x21, Ld(DirectRegister16("HL".to_string()), U16), 3, 12, 12),
        Instruction::new(0x22, Ld(Hli, DirectRegister8("A".to_string())), 1, 8, 8),
        Instruction::new(0x23, Inc(DirectRegister16("HL".to_string())), 1, 8, 8),
        Instruction::new(0x24, Inc(DirectRegister8("H".to_string())), 1, 4, 4),
        Instruction::new(0x25, Dec(DirectRegister8("H".to_string())), 1, 4, 4),
        Instruction::new(0x26, Ld(DirectRegister8("H".to_string()), U8), 2, 8, 8),
        Instruction::new(0x27, Daa, 1, 4, 4),
        Instruction::new(0x28, Jr(Condition("Z".to_string())), 2, 12, 8),
        Instruction::new(
            0x29,
            Add(
                DirectRegister16("HL".to_string()),
                DirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(0x2A, Ld(DirectRegister8("A".to_string()), Hli), 1, 8, 8),
        Instruction::new(0x2B, Dec(DirectRegister16("HL".to_string())), 1, 8, 8),
        Instruction::new(0x2C, Inc(DirectRegister8("L".to_string())), 1, 4, 4),
        Instruction::new(0x2D, Dec(DirectRegister8("L".to_string())), 1, 4, 4),
        Instruction::new(0x2E, Ld(DirectRegister8("L".to_string()), U8), 2, 8, 8),
        Instruction::new(0x2F, Cpl, 1, 4, 4),
        Instruction::new(0x30, Jr(Condition("NC".to_string())), 2, 12, 8),
        Instruction::new(0x31, Ld(DirectRegister16("SP".to_string()), U16), 3, 12, 12),
        Instruction::new(0x32, Ld(Hld, DirectRegister8("A".to_string())), 1, 8, 8),
        Instruction::new(0x33, Inc(DirectRegister16("SP".to_string())), 1, 8, 8),
        Instruction::new(0x34, Inc(IndirectRegister16("HL".to_string())), 1, 12, 12),
        Instruction::new(0x35, Dec(IndirectRegister16("HL".to_string())), 1, 12, 12),
        Instruction::new(
            0x36,
            Ld(IndirectRegister16("HL".to_string()), U8),
            2,
            12,
            12,
        ),
        Instruction::new(0x37, Scf, 1, 4, 4),
        Instruction::new(0x38, Jr(Condition("C".to_string())), 2, 12, 8),
        Instruction::new(
            0x39,
            Add(
                DirectRegister16("HL".to_string()),
                DirectRegister16("SP".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(0x3A, Ld(DirectRegister8("A".to_string()), Hld), 1, 8, 8),
        Instruction::new(0x3B, Dec(DirectRegister16("SP".to_string())), 1, 8, 8),
        Instruction::new(0x3C, Inc(DirectRegister8("A".to_string())), 1, 4, 4),
        Instruction::new(0x3D, Dec(DirectRegister8("A".to_string())), 1, 4, 4),
        Instruction::new(0x3E, Ld(DirectRegister8("A".to_string()), U8), 2, 8, 8),
        Instruction::new(0x3F, Ccf, 1, 4, 4),
        Instruction::new(
            0x40,
            Ld(
                DirectRegister8("B".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x41,
            Ld(
                DirectRegister8("B".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x42,
            Ld(
                DirectRegister8("B".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x43,
            Ld(
                DirectRegister8("B".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x44,
            Ld(
                DirectRegister8("B".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x45,
            Ld(
                DirectRegister8("B".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x46,
            Ld(
                DirectRegister8("B".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x47,
            Ld(
                DirectRegister8("B".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x48,
            Ld(
                DirectRegister8("C".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x49,
            Ld(
                DirectRegister8("C".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x4A,
            Ld(
                DirectRegister8("C".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x4B,
            Ld(
                DirectRegister8("C".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x4C,
            Ld(
                DirectRegister8("C".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x4D,
            Ld(
                DirectRegister8("C".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x4E,
            Ld(
                DirectRegister8("C".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x4F,
            Ld(
                DirectRegister8("C".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x50,
            Ld(
                DirectRegister8("D".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x51,
            Ld(
                DirectRegister8("D".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x52,
            Ld(
                DirectRegister8("D".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x53,
            Ld(
                DirectRegister8("D".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x54,
            Ld(
                DirectRegister8("D".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x55,
            Ld(
                DirectRegister8("D".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x56,
            Ld(
                DirectRegister8("D".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x57,
            Ld(
                DirectRegister8("D".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x58,
            Ld(
                DirectRegister8("E".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x59,
            Ld(
                DirectRegister8("E".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x5A,
            Ld(
                DirectRegister8("E".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x5B,
            Ld(
                DirectRegister8("E".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x5C,
            Ld(
                DirectRegister8("E".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x5D,
            Ld(
                DirectRegister8("E".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x5E,
            Ld(
                DirectRegister8("E".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x5F,
            Ld(
                DirectRegister8("E".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x60,
            Ld(
                DirectRegister8("H".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x61,
            Ld(
                DirectRegister8("H".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x62,
            Ld(
                DirectRegister8("H".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x63,
            Ld(
                DirectRegister8("H".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x64,
            Ld(
                DirectRegister8("H".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x65,
            Ld(
                DirectRegister8("H".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x66,
            Ld(
                DirectRegister8("H".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x67,
            Ld(
                DirectRegister8("H".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x68,
            Ld(
                DirectRegister8("L".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x69,
            Ld(
                DirectRegister8("L".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x6A,
            Ld(
                DirectRegister8("L".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x6B,
            Ld(
                DirectRegister8("L".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x6C,
            Ld(
                DirectRegister8("L".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x6D,
            Ld(
                DirectRegister8("L".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x6E,
            Ld(
                DirectRegister8("L".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x6F,
            Ld(
                DirectRegister8("L".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x70,
            Ld(
                IndirectRegister16("HL".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x71,
            Ld(
                IndirectRegister16("HL".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x72,
            Ld(
                IndirectRegister16("HL".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x73,
            Ld(
                IndirectRegister16("HL".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x74,
            Ld(
                IndirectRegister16("HL".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x75,
            Ld(
                IndirectRegister16("HL".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(0x76, Halt, 1, 4, 4),
        Instruction::new(
            0x77,
            Ld(
                IndirectRegister16("HL".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x78,
            Ld(
                DirectRegister8("A".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x79,
            Ld(
                DirectRegister8("A".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x7A,
            Ld(
                DirectRegister8("A".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x7B,
            Ld(
                DirectRegister8("A".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x7C,
            Ld(
                DirectRegister8("A".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x7D,
            Ld(
                DirectRegister8("A".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x7E,
            Ld(
                DirectRegister8("A".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x7F,
            Ld(
                DirectRegister8("A".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x80,
            Add(
                DirectRegister8("A".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x81,
            Add(
                DirectRegister8("A".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x82,
            Add(
                DirectRegister8("A".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x83,
            Add(
                DirectRegister8("A".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x84,
            Add(
                DirectRegister8("A".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x85,
            Add(
                DirectRegister8("A".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x86,
            Add(
                DirectRegister8("A".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x87,
            Add(
                DirectRegister8("A".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x88,
            Adc(
                DirectRegister8("A".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x89,
            Adc(
                DirectRegister8("A".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x8A,
            Adc(
                DirectRegister8("A".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x8B,
            Adc(
                DirectRegister8("A".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x8C,
            Adc(
                DirectRegister8("A".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x8D,
            Adc(
                DirectRegister8("A".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x8E,
            Adc(
                DirectRegister8("A".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x8F,
            Adc(
                DirectRegister8("A".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x90,
            Sub(
                DirectRegister8("A".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x91,
            Sub(
                DirectRegister8("A".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x92,
            Sub(
                DirectRegister8("A".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x93,
            Sub(
                DirectRegister8("A".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x94,
            Sub(
                DirectRegister8("A".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x95,
            Sub(
                DirectRegister8("A".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x96,
            Sub(
                DirectRegister8("A".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x97,
            Sub(
                DirectRegister8("A".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x98,
            Sbc(
                DirectRegister8("A".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x99,
            Sbc(
                DirectRegister8("A".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x9A,
            Sbc(
                DirectRegister8("A".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x9B,
            Sbc(
                DirectRegister8("A".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x9C,
            Sbc(
                DirectRegister8("A".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x9D,
            Sbc(
                DirectRegister8("A".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0x9E,
            Sbc(
                DirectRegister8("A".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0x9F,
            Sbc(
                DirectRegister8("A".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xA0,
            And(
                DirectRegister8("A".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xA1,
            And(
                DirectRegister8("A".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xA2,
            And(
                DirectRegister8("A".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xA3,
            And(
                DirectRegister8("A".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xA4,
            And(
                DirectRegister8("A".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xA5,
            And(
                DirectRegister8("A".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xA6,
            And(
                DirectRegister8("A".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0xA7,
            And(
                DirectRegister8("A".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xA8,
            Xor(
                DirectRegister8("A".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xA9,
            Xor(
                DirectRegister8("A".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xAA,
            Xor(
                DirectRegister8("A".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xAB,
            Xor(
                DirectRegister8("A".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xAC,
            Xor(
                DirectRegister8("A".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xAD,
            Xor(
                DirectRegister8("A".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xAE,
            Xor(
                DirectRegister8("A".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0xAF,
            Xor(
                DirectRegister8("A".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xB0,
            Or(
                DirectRegister8("A".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xB1,
            Or(
                DirectRegister8("A".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xB2,
            Or(
                DirectRegister8("A".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xB3,
            Or(
                DirectRegister8("A".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xB4,
            Or(
                DirectRegister8("A".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xB5,
            Or(
                DirectRegister8("A".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xB6,
            Or(
                DirectRegister8("A".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0xB7,
            Or(
                DirectRegister8("A".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xB8,
            Cp(
                DirectRegister8("A".to_string()),
                DirectRegister8("B".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xB9,
            Cp(
                DirectRegister8("A".to_string()),
                DirectRegister8("C".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xBA,
            Cp(
                DirectRegister8("A".to_string()),
                DirectRegister8("D".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xBB,
            Cp(
                DirectRegister8("A".to_string()),
                DirectRegister8("E".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xBC,
            Cp(
                DirectRegister8("A".to_string()),
                DirectRegister8("H".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xBD,
            Cp(
                DirectRegister8("A".to_string()),
                DirectRegister8("L".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(
            0xBE,
            Cp(
                DirectRegister8("A".to_string()),
                IndirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0xBF,
            Cp(
                DirectRegister8("A".to_string()),
                DirectRegister8("A".to_string()),
            ),
            1,
            4,
            4,
        ),
        Instruction::new(0xC0, Ret, 1, 20, 8),
        Instruction::new(0xC1, Pop(DirectRegister16("BC".to_string())), 1, 12, 12),
        Instruction::new(0xC2, Jp(Condition("NZ".to_string())), 3, 16, 12),
        Instruction::new(0xC3, Jp(U16), 3, 16, 16),
        Instruction::new(0xC4, Call(Condition("NZ".to_string())), 3, 24, 12),
        Instruction::new(0xC5, Push(DirectRegister16("BC".to_string())), 1, 16, 16),
        Instruction::new(0xC6, Add(DirectRegister8("A".to_string()), U8), 2, 8, 8),
        Instruction::new(0xC7, Rst(Vector("00h".to_string())), 1, 16, 16),
        Instruction::new(0xC8, Ret, 1, 20, 8),
        Instruction::new(0xC9, Ret, 1, 16, 16),
        Instruction::new(0xCA, Jp(Condition("Z".to_string())), 3, 16, 12),
        Instruction::new(0xCC, Call(Condition("Z".to_string())), 3, 24, 12),
        Instruction::new(0xCD, Call(U16), 3, 24, 24),
        Instruction::new(0xCE, Adc(DirectRegister8("A".to_string()), U8), 2, 8, 8),
        Instruction::new(0xCF, Rst(Vector("08h".to_string())), 1, 16, 16),
        Instruction::new(0xD0, Ret, 1, 20, 8),
        Instruction::new(0xD1, Pop(DirectRegister16("DE".to_string())), 1, 12, 12),
        Instruction::new(0xD2, Jp(Condition("NC".to_string())), 3, 16, 12),
        Instruction::new(0xD4, Call(Condition("NC".to_string())), 3, 24, 12),
        Instruction::new(0xD5, Push(DirectRegister16("DE".to_string())), 1, 16, 16),
        Instruction::new(0xD6, Sub(DirectRegister8("A".to_string()), U8), 2, 8, 8),
        Instruction::new(0xD7, Rst(Vector("10h".to_string())), 1, 16, 16),
        Instruction::new(0xD8, Ret, 1, 20, 8),
        Instruction::new(0xD9, Reti, 1, 16, 16),
        Instruction::new(0xDA, Jp(Condition("C".to_string())), 3, 16, 12),
        Instruction::new(0xDC, Call(Condition("C".to_string())), 3, 24, 12),
        Instruction::new(0xDE, Sbc(DirectRegister8("A".to_string()), U8), 2, 8, 8),
        Instruction::new(0xDF, Rst(Vector("18h".to_string())), 1, 16, 16),
        Instruction::new(
            0xE0,
            Ld(IndirectFF00PlusU8, DirectRegister8("A".to_string())),
            2,
            12,
            12,
        ),
        Instruction::new(0xE1, Pop(DirectRegister16("HL".to_string())), 1, 12, 12),
        Instruction::new(
            0xE2,
            Ld(IndirectFF00PlusC, DirectRegister8("A".to_string())),
            1,
            8,
            8,
        ),
        Instruction::new(0xE5, Push(DirectRegister16("HL".to_string())), 1, 16, 16),
        Instruction::new(0xE6, And(DirectRegister8("A".to_string()), U8), 2, 8, 8),
        Instruction::new(0xE7, Rst(Vector("20h".to_string())), 1, 16, 16),
        Instruction::new(0xE8, Add(DirectRegister16("SP".to_string()), I8), 2, 16, 16),
        Instruction::new(0xE9, Jp(DirectRegister16("HL".to_string())), 1, 4, 4),
        Instruction::new(
            0xEA,
            Ld(IndirectU16, DirectRegister8("A".to_string())),
            3,
            16,
            16,
        ),
        Instruction::new(0xEE, Xor(DirectRegister8("A".to_string()), U8), 2, 8, 8),
        Instruction::new(0xEF, Rst(Vector("28h".to_string())), 1, 16, 16),
        Instruction::new(
            0xF0,
            Ld(DirectRegister8("A".to_string()), IndirectFF00PlusU8),
            2,
            12,
            12,
        ),
        Instruction::new(0xF1, Pop(DirectRegister16("AF".to_string())), 1, 12, 12),
        Instruction::new(
            0xF2,
            Ld(DirectRegister8("A".to_string()), IndirectFF00PlusC),
            1,
            8,
            8,
        ),
        Instruction::new(0xF3, Di, 1, 4, 4),
        Instruction::new(0xF5, Push(DirectRegister16("AF".to_string())), 1, 16, 16),
        Instruction::new(0xF6, Or(DirectRegister8("A".to_string()), U8), 2, 8, 8),
        Instruction::new(0xF7, Rst(Vector("30h".to_string())), 1, 16, 16),
        Instruction::new(
            0xF8,
            Ld(DirectRegister16("HL".to_string()), SpPlusI8),
            2,
            12,
            12,
        ),
        Instruction::new(
            0xF9,
            Ld(
                DirectRegister16("SP".to_string()),
                DirectRegister16("HL".to_string()),
            ),
            1,
            8,
            8,
        ),
        Instruction::new(
            0xFA,
            Ld(DirectRegister8("A".to_string()), IndirectU16),
            3,
            16,
            16,
        ),
        Instruction::new(0xFB, Ei, 1, 4, 4),
        Instruction::new(0xFE, Cp(DirectRegister8("A".to_string()), U8), 2, 8, 8),
        Instruction::new(0xFF, Rst(Vector("38h".to_string())), 1, 16, 16),
        Instruction::new(0xCB00, Rlc(DirectRegister8("B".to_string())), 2, 8, 8),
        Instruction::new(0xCB01, Rlc(DirectRegister8("C".to_string())), 2, 8, 8),
        Instruction::new(0xCB02, Rlc(DirectRegister8("D".to_string())), 2, 8, 8),
        Instruction::new(0xCB03, Rlc(DirectRegister8("E".to_string())), 2, 8, 8),
        Instruction::new(0xCB04, Rlc(DirectRegister8("H".to_string())), 2, 8, 8),
        Instruction::new(0xCB05, Rlc(DirectRegister8("L".to_string())), 2, 8, 8),
        Instruction::new(0xCB06, Rlc(IndirectRegister16("HL".to_string())), 2, 16, 16),
        Instruction::new(0xCB07, Rlc(DirectRegister8("A".to_string())), 2, 8, 8),
        Instruction::new(0xCB08, Rrc(DirectRegister8("B".to_string())), 2, 8, 8),
        Instruction::new(0xCB09, Rrc(DirectRegister8("C".to_string())), 2, 8, 8),
        Instruction::new(0xCB0A, Rrc(DirectRegister8("D".to_string())), 2, 8, 8),
        Instruction::new(0xCB0B, Rrc(DirectRegister8("E".to_string())), 2, 8, 8),
        Instruction::new(0xCB0C, Rrc(DirectRegister8("H".to_string())), 2, 8, 8),
        Instruction::new(0xCB0D, Rrc(DirectRegister8("L".to_string())), 2, 8, 8),
        Instruction::new(0xCB0E, Rrc(IndirectRegister16("HL".to_string())), 2, 16, 16),
        Instruction::new(0xCB0F, Rrc(DirectRegister8("A".to_string())), 2, 8, 8),
        Instruction::new(0xCB10, Rl(DirectRegister8("B".to_string())), 2, 8, 8),
        Instruction::new(0xCB11, Rl(DirectRegister8("C".to_string())), 2, 8, 8),
        Instruction::new(0xCB12, Rl(DirectRegister8("D".to_string())), 2, 8, 8),
        Instruction::new(0xCB13, Rl(DirectRegister8("E".to_string())), 2, 8, 8),
        Instruction::new(0xCB14, Rl(DirectRegister8("H".to_string())), 2, 8, 8),
        Instruction::new(0xCB15, Rl(DirectRegister8("L".to_string())), 2, 8, 8),
        Instruction::new(0xCB16, Rl(IndirectRegister16("HL".to_string())), 2, 16, 16),
        Instruction::new(0xCB17, Rl(DirectRegister8("A".to_string())), 2, 8, 8),
        Instruction::new(0xCB18, Rr(DirectRegister8("B".to_string())), 2, 8, 8),
        Instruction::new(0xCB19, Rr(DirectRegister8("C".to_string())), 2, 8, 8),
        Instruction::new(0xCB1A, Rr(DirectRegister8("D".to_string())), 2, 8, 8),
        Instruction::new(0xCB1B, Rr(DirectRegister8("E".to_string())), 2, 8, 8),
        Instruction::new(0xCB1C, Rr(DirectRegister8("H".to_string())), 2, 8, 8),
        Instruction::new(0xCB1D, Rr(DirectRegister8("L".to_string())), 2, 8, 8),
        Instruction::new(0xCB1E, Rr(IndirectRegister16("HL".to_string())), 2, 16, 16),
        Instruction::new(0xCB1F, Rr(DirectRegister8("A".to_string())), 2, 8, 8),
        Instruction::new(0xCB20, Sla(DirectRegister8("B".to_string())), 2, 8, 8),
        Instruction::new(0xCB21, Sla(DirectRegister8("C".to_string())), 2, 8, 8),
        Instruction::new(0xCB22, Sla(DirectRegister8("D".to_string())), 2, 8, 8),
        Instruction::new(0xCB23, Sla(DirectRegister8("E".to_string())), 2, 8, 8),
        Instruction::new(0xCB24, Sla(DirectRegister8("H".to_string())), 2, 8, 8),
        Instruction::new(0xCB25, Sla(DirectRegister8("L".to_string())), 2, 8, 8),
        Instruction::new(0xCB26, Sla(IndirectRegister16("HL".to_string())), 2, 16, 16),
        Instruction::new(0xCB27, Sla(DirectRegister8("A".to_string())), 2, 8, 8),
        Instruction::new(0xCB28, Sra(DirectRegister8("B".to_string())), 2, 8, 8),
        Instruction::new(0xCB29, Sra(DirectRegister8("C".to_string())), 2, 8, 8),
        Instruction::new(0xCB2A, Sra(DirectRegister8("D".to_string())), 2, 8, 8),
        Instruction::new(0xCB2B, Sra(DirectRegister8("E".to_string())), 2, 8, 8),
        Instruction::new(0xCB2C, Sra(DirectRegister8("H".to_string())), 2, 8, 8),
        Instruction::new(0xCB2D, Sra(DirectRegister8("L".to_string())), 2, 8, 8),
        Instruction::new(0xCB2E, Sra(IndirectRegister16("HL".to_string())), 2, 16, 16),
        Instruction::new(0xCB2F, Sra(DirectRegister8("A".to_string())), 2, 8, 8),
        Instruction::new(0xCB30, Swap(DirectRegister8("B".to_string())), 2, 8, 8),
        Instruction::new(0xCB31, Swap(DirectRegister8("C".to_string())), 2, 8, 8),
        Instruction::new(0xCB32, Swap(DirectRegister8("D".to_string())), 2, 8, 8),
        Instruction::new(0xCB33, Swap(DirectRegister8("E".to_string())), 2, 8, 8),
        Instruction::new(0xCB34, Swap(DirectRegister8("H".to_string())), 2, 8, 8),
        Instruction::new(0xCB35, Swap(DirectRegister8("L".to_string())), 2, 8, 8),
        Instruction::new(
            0xCB36,
            Swap(IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(0xCB37, Swap(DirectRegister8("A".to_string())), 2, 8, 8),
        Instruction::new(0xCB38, Srl(DirectRegister8("B".to_string())), 2, 8, 8),
        Instruction::new(0xCB39, Srl(DirectRegister8("C".to_string())), 2, 8, 8),
        Instruction::new(0xCB3A, Srl(DirectRegister8("D".to_string())), 2, 8, 8),
        Instruction::new(0xCB3B, Srl(DirectRegister8("E".to_string())), 2, 8, 8),
        Instruction::new(0xCB3C, Srl(DirectRegister8("H".to_string())), 2, 8, 8),
        Instruction::new(0xCB3D, Srl(DirectRegister8("L".to_string())), 2, 8, 8),
        Instruction::new(0xCB3E, Srl(IndirectRegister16("HL".to_string())), 2, 16, 16),
        Instruction::new(0xCB3F, Srl(DirectRegister8("A".to_string())), 2, 8, 8),
        Instruction::new(
            0xCB40,
            Bit(Literal(0), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB41,
            Bit(Literal(0), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB42,
            Bit(Literal(0), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB43,
            Bit(Literal(0), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB44,
            Bit(Literal(0), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB45,
            Bit(Literal(0), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB46,
            Bit(Literal(0), IndirectRegister16("HL".to_string())),
            2,
            12,
            12,
        ),
        Instruction::new(
            0xCB47,
            Bit(Literal(0), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB48,
            Bit(Literal(1), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB49,
            Bit(Literal(1), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB4A,
            Bit(Literal(1), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB4B,
            Bit(Literal(1), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB4C,
            Bit(Literal(1), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB4D,
            Bit(Literal(1), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB4E,
            Bit(Literal(1), IndirectRegister16("HL".to_string())),
            2,
            12,
            12,
        ),
        Instruction::new(
            0xCB4F,
            Bit(Literal(1), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB50,
            Bit(Literal(2), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB51,
            Bit(Literal(2), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB52,
            Bit(Literal(2), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB53,
            Bit(Literal(2), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB54,
            Bit(Literal(2), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB55,
            Bit(Literal(2), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB56,
            Bit(Literal(2), IndirectRegister16("HL".to_string())),
            2,
            12,
            12,
        ),
        Instruction::new(
            0xCB57,
            Bit(Literal(2), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB58,
            Bit(Literal(3), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB59,
            Bit(Literal(3), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB5A,
            Bit(Literal(3), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB5B,
            Bit(Literal(3), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB5C,
            Bit(Literal(3), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB5D,
            Bit(Literal(3), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB5E,
            Bit(Literal(3), IndirectRegister16("HL".to_string())),
            2,
            12,
            12,
        ),
        Instruction::new(
            0xCB5F,
            Bit(Literal(3), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB60,
            Bit(Literal(4), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB61,
            Bit(Literal(4), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB62,
            Bit(Literal(4), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB63,
            Bit(Literal(4), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB64,
            Bit(Literal(4), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB65,
            Bit(Literal(4), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB66,
            Bit(Literal(4), IndirectRegister16("HL".to_string())),
            2,
            12,
            12,
        ),
        Instruction::new(
            0xCB67,
            Bit(Literal(4), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB68,
            Bit(Literal(5), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB69,
            Bit(Literal(5), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB6A,
            Bit(Literal(5), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB6B,
            Bit(Literal(5), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB6C,
            Bit(Literal(5), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB6D,
            Bit(Literal(5), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB6E,
            Bit(Literal(5), IndirectRegister16("HL".to_string())),
            2,
            12,
            12,
        ),
        Instruction::new(
            0xCB6F,
            Bit(Literal(5), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB70,
            Bit(Literal(6), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB71,
            Bit(Literal(6), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB72,
            Bit(Literal(6), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB73,
            Bit(Literal(6), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB74,
            Bit(Literal(6), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB75,
            Bit(Literal(6), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB76,
            Bit(Literal(6), IndirectRegister16("HL".to_string())),
            2,
            12,
            12,
        ),
        Instruction::new(
            0xCB77,
            Bit(Literal(6), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB78,
            Bit(Literal(7), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB79,
            Bit(Literal(7), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB7A,
            Bit(Literal(7), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB7B,
            Bit(Literal(7), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB7C,
            Bit(Literal(7), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB7D,
            Bit(Literal(7), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB7E,
            Bit(Literal(7), IndirectRegister16("HL".to_string())),
            2,
            12,
            12,
        ),
        Instruction::new(
            0xCB7F,
            Bit(Literal(7), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB80,
            Res(Literal(0), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB81,
            Res(Literal(0), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB82,
            Res(Literal(0), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB83,
            Res(Literal(0), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB84,
            Res(Literal(0), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB85,
            Res(Literal(0), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB86,
            Res(Literal(0), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCB87,
            Res(Literal(0), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB88,
            Res(Literal(1), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB89,
            Res(Literal(1), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB8A,
            Res(Literal(1), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB8B,
            Res(Literal(1), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB8C,
            Res(Literal(1), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB8D,
            Res(Literal(1), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB8E,
            Res(Literal(1), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCB8F,
            Res(Literal(1), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB90,
            Res(Literal(2), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB91,
            Res(Literal(2), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB92,
            Res(Literal(2), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB93,
            Res(Literal(2), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB94,
            Res(Literal(2), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB95,
            Res(Literal(2), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB96,
            Res(Literal(2), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCB97,
            Res(Literal(2), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB98,
            Res(Literal(3), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB99,
            Res(Literal(3), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB9A,
            Res(Literal(3), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB9B,
            Res(Literal(3), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB9C,
            Res(Literal(3), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB9D,
            Res(Literal(3), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCB9E,
            Res(Literal(3), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCB9F,
            Res(Literal(3), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBA0,
            Res(Literal(4), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBA1,
            Res(Literal(4), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBA2,
            Res(Literal(4), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBA3,
            Res(Literal(4), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBA4,
            Res(Literal(4), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBA5,
            Res(Literal(4), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBA6,
            Res(Literal(4), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBA7,
            Res(Literal(4), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBA8,
            Res(Literal(5), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBA9,
            Res(Literal(5), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBAA,
            Res(Literal(5), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBAB,
            Res(Literal(5), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBAC,
            Res(Literal(5), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBAD,
            Res(Literal(5), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBAE,
            Res(Literal(5), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBAF,
            Res(Literal(5), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBB0,
            Res(Literal(6), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBB1,
            Res(Literal(6), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBB2,
            Res(Literal(6), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBB3,
            Res(Literal(6), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBB4,
            Res(Literal(6), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBB5,
            Res(Literal(6), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBB6,
            Res(Literal(6), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBB7,
            Res(Literal(6), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBB8,
            Res(Literal(7), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBB9,
            Res(Literal(7), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBBA,
            Res(Literal(7), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBBB,
            Res(Literal(7), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBBC,
            Res(Literal(7), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBBD,
            Res(Literal(7), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBBE,
            Res(Literal(7), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBBF,
            Res(Literal(7), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBC0,
            Set(Literal(0), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBC1,
            Set(Literal(0), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBC2,
            Set(Literal(0), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBC3,
            Set(Literal(0), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBC4,
            Set(Literal(0), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBC5,
            Set(Literal(0), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBC6,
            Set(Literal(0), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBC7,
            Set(Literal(0), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBC8,
            Set(Literal(1), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBC9,
            Set(Literal(1), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBCA,
            Set(Literal(1), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBCB,
            Set(Literal(1), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBCC,
            Set(Literal(1), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBCD,
            Set(Literal(1), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBCE,
            Set(Literal(1), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBCF,
            Set(Literal(1), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBD0,
            Set(Literal(2), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBD1,
            Set(Literal(2), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBD2,
            Set(Literal(2), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBD3,
            Set(Literal(2), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBD4,
            Set(Literal(2), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBD5,
            Set(Literal(2), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBD6,
            Set(Literal(2), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBD7,
            Set(Literal(2), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBD8,
            Set(Literal(3), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBD9,
            Set(Literal(3), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBDA,
            Set(Literal(3), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBDB,
            Set(Literal(3), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBDC,
            Set(Literal(3), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBDD,
            Set(Literal(3), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBDE,
            Set(Literal(3), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBDF,
            Set(Literal(3), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBE0,
            Set(Literal(4), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBE1,
            Set(Literal(4), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBE2,
            Set(Literal(4), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBE3,
            Set(Literal(4), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBE4,
            Set(Literal(4), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBE5,
            Set(Literal(4), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBE6,
            Set(Literal(4), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBE7,
            Set(Literal(4), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBE8,
            Set(Literal(5), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBE9,
            Set(Literal(5), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBEA,
            Set(Literal(5), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBEB,
            Set(Literal(5), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBEC,
            Set(Literal(5), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBED,
            Set(Literal(5), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBEE,
            Set(Literal(5), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBEF,
            Set(Literal(5), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBF0,
            Set(Literal(6), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBF1,
            Set(Literal(6), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBF2,
            Set(Literal(6), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBF3,
            Set(Literal(6), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBF4,
            Set(Literal(6), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBF5,
            Set(Literal(6), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBF6,
            Set(Literal(6), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBF7,
            Set(Literal(6), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBF8,
            Set(Literal(7), DirectRegister8("B".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBF9,
            Set(Literal(7), DirectRegister8("C".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBFA,
            Set(Literal(7), DirectRegister8("D".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBFB,
            Set(Literal(7), DirectRegister8("E".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBFC,
            Set(Literal(7), DirectRegister8("H".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBFD,
            Set(Literal(7), DirectRegister8("L".to_string())),
            2,
            8,
            8,
        ),
        Instruction::new(
            0xCBFE,
            Set(Literal(7), IndirectRegister16("HL".to_string())),
            2,
            16,
            16,
        ),
        Instruction::new(
            0xCBFF,
            Set(Literal(7), DirectRegister8("A".to_string())),
            2,
            8,
            8,
        ),
    ]
}
